# Generated by Django 3.1.6 on 2021-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='交易id')),
                ('sum_value', models.FloatField(max_length=10, verbose_name='消费或收入金额')),
                ('date_value', models.DateField(verbose_name='消费日期')),
                ('time_value', models.TimeField(verbose_name='消费时间')),
                ('remarkd_value', models.CharField(max_length=100, verbose_name='备注')),
                ('account_type', models.CharField(max_length=20, verbose_name='消费类型')),
                ('billTypeNumber', models.CharField(max_length=20, verbose_name='简称')),
                ('consumption_or_earn', models.BooleanField(verbose_name='消费或收入')),
            ],
        ),
    ]
