# Generated by Django 3.1.6 on 2021-03-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='remarkd_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='备注'),
        ),
    ]
