# Generated by Django 3.1.6 on 2021-03-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210320_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='remarkd_value',
            new_name='remarks_value',
        ),
    ]
