# Generated by Django 3.1.6 on 2021-03-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_balance',
            field=models.FloatField(default='0.0', max_length=100, verbose_name='当前余额'),
        ),
    ]
